// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncjralbawkvsvpsrnpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY2pyYWxiYXdrdnN2cHNybnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODcwNjUsImV4cCI6MjA2NjA2MzA2NX0.nfXH_2NHH2gdc6mF2tsIv5DklBzG8kPRbloOItxE1Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});